# -*- coding: utf-8 -*-
matches = {
    "gui.QgsMapLayerModel": "core.QgsMapLayerModel",
    "gui.QgsMapLayerProxyModel": "core.QgsMapLayerProxyModel",
    "QgisGui": "QgsGuiUtils",
    "QgsAbstractGeometryV2": "QgsAbstractGeometry",
    "QgsArcProperter": "QgsStrategy",
    "QgsAttributeAction": "QgsActionManager",
    "QgsCategorizedSymbolRendererV2": "QgsCategorizedSymbolRenderer",
    "QgsCategorizedSymbolRendererV2Model": "QgsCategorizedSymbolRendererModel",
    "QgsCategorizedSymbolRendererV2ViewStyle": "QgsCategorizedSymbolRendererViewStyle",
    "QgsCategorizedSymbolRendererV2Widget": "QgsCategorizedSymbolRendererWidget",
    "QgsCentroidFillSymbolLayerV2": "QgsCentroidFillSymbolLayer",
    "QgsCentroidFillSymbolLayerV2Widget": "QgsCentroidFillSymbolLayerWidget",
    "QgsCircularStringV2": "QgsCircularString",
    "QgsColorButtonV2": "QgsColorButton",
    "QgsCompoundCurveV2": "QgsCompoundCurve",
    "QgsCoordinateSequenceV2": "QgsCoordinateSequence",
    "QgsCptCityColorRampV2": "QgsCptCityColorRamp",
    "QgsCptCityColorRampV2Dialog": "QgsCptCityColorRampDialog",
    "QgsCptCityColorRampV2DialogBase": "QgsCptCityColorRampDialogBase",
    "QgsCurvePolygonV2": "QgsCurvePolygon",
    "QgsCurveV2": "QgsCurve",
    "QgsDbFilterProxyModel": "QgsDatabaseFilterProxyModel",
    "QgsDiagramRendererV2": "QgsDiagramRenderer",
    "QgsDistanceArcProperter": "QgsDistanceStrategy",
    "QgsDoubleBoxBarStyle": "QgsDoubleBoxScaleBarRenderer",
    "QgsEditorWidgetV2": "QgsEditorWidget",
    "QgsEllipseSymbolLayerV2": "QgsEllipseSymbolLayer",
    "QgsEllipseSymbolLayerV2Widget": "QgsEllipseSymbolLayerWidget",
    "QgsFavouritesItem": "QgsFavoritesItem",
    "QgsFeatureRendererV2": "QgsFeatureRenderer",
    "QgsFillSymbolLayerV2": "QgsFillSymbolLayer",
    "QgsFillSymbolV2": "QgsFillSymbol",
    "QgsFontMarkerSymbolLayerV2": "QgsFontMarkerSymbolLayer",
    "QgsFontMarkerSymbolLayerV2Widget": "QgsFontMarkerSymbolLayerWidget",
    "QgsGeometryCollectionV2": "QgsGeometryCollection",
    "QgsGeometryGeneratorSymbolLayerV2": "QgsGeometryGeneratorSymbolLayer",
    "QgsGPSConnection": "QgsGpsConnection",
    "QgsGPSConnectionRegistry": "QgsGpsConnectionRegistry",
    "QgsGPSDetector": "QgsGpsDetector",
    "QgsGPSInformation": "QgsGpsInformation",
    "QgsGradientFillSymbolLayerV2": "QgsGradientFillSymbolLayer",
    "QgsGradientFillSymbolLayerV2Widget": "QgsGradientFillSymbolLayerWidget",
    "QgsGraduatedSymbolRendererV2": "QgsGraduatedSymbolRenderer",
    "QgsGraduatedSymbolRendererV2Model": "QgsGraduatedSymbolRendererModel",
    "QgsGraduatedSymbolRendererV2ViewStyle": "QgsGraduatedSymbolRendererViewStyle",
    "QgsGraduatedSymbolRendererV2Widget": "QgsGraduatedSymbolRendererWidget",
    "QgsGraphArc": "QgsGraphEdge",
    "QgsJSONExporter": "QgsJsonExporter",
    "QgsJSONUtils": "QgsJsonUtils",
    "QgsLabelingEngineV2": "QgsLabelingEngine",
    "QgsLegendModelV2": "QgsLegendModel",
    "QgsLegendSymbolItemV2": "QgsLegendSymbolItem",
    "QgsLineStringV2": "QgsLineString",
    "QgsLineSymbolLayerV2": "QgsLineSymbolLayer",
    "QgsLineSymbolV2": "QgsLineSymbol",
    "QgsMarkerLineSymbolLayerV2": "QgsMarkerLineSymbolLayer",
    "QgsMarkerLineSymbolLayerV2Widget": "QgsMarkerLineSymbolLayerWidget",
    "QgsMarkerSymbolLayerV2": "QgsMarkerSymbolLayer",
    "QgsMarkerSymbolV2": "QgsMarkerSymbol",
    "QgsMultiCurveV2": "QgsMultiCurve",
    "QgsMultiLineStringV2": "QgsMultiLineString",
    "QgsMultiPoint": "QgsMultiPointXY",
    "QgsMultiPointV2": "QgsMultiPoint",
    "QgsMultiPolygon": "QgsPolygonXY",
    "QgsMultiPolygonV2": "QgsPolygon",
    "QgsMultiPolyline": "QgsPolylineXY",
    "QgsMultiPolylineV2": "QgsPolyline",
    "QgsMultiSurfaceV2": "QgsMultiSurface",
    "QgsNMEAConnection": "QgsNmeaConnection",
    "QgsNodeEditor": "QgsVertexEditor",
    "QgsNodeTool": "QgsVertexTool",
    "QgsNumericScaleBarStyle": "QgsNumericScaleBarRenderer",
    "QgsPoint": "QgsPointXY",
    "QgsPointSequenceV2": "QgsPointSequence",
    "QgsPointV2": "QgsPoint",
    "QgsPolygon": "QgsPolygonXY",
    "QgsPolygonV2": "QgsPolygon",
    "QgsPolyline": "QgsPolylineXY",
    "QgsPolylineV2": "QgsPolyline",
    "QgsProperty": "QgsProjectProperty",
    "QgsPropertyKey": "QgsProjectPropertyKey",
    "QgsPropertyValue": "QgsProjectPropertyValue",
    "QgsRandomColorsV2": "QgsRandomColorRamp",
    "QgsRendererCategoryV2": "QgsRendererCategory",
    "QgsRendererRangeV2": "QgsRendererRange",
    "QgsRendererRangeV2LabelFomat": "QgsRendererRangeLabelFomat",
    "QgsRendererRangeV2LabelFormat": "QgsRendererRangeLabelFormat",
    "QgsRendererV2": "QgsRenderer",
    "QgsRendererV2AbstractMetadata": "QgsRendererAbstractMetadata",
    "QgsRendererV2CreateFromSldFunc": "QgsRendererCreateFromSldFunc",
    "QgsRendererV2CreateFunc": "QgsRendererCreateFunc",
    "QgsRendererV2DataDefinedMenus": "QgsRendererDataDefinedMenus",
    "QgsRendererV2Metadata": "QgsRendererMetadata",
    "QgsRendererV2PropertiesDialog": "QgsRendererPropertiesDialog",
    "QgsRendererV2PropsDialogBase": "QgsRendererPropsDialogBase",
    "QgsRendererV2Registry": "QgsRendererRegistry",
    "QgsRendererV2Widget": "QgsRendererWidget",
    "QgsRendererV2WidgetFunc": "QgsRendererWidgetFunc",
    "QgsRingSequenceV2": "QgsRingSequence",
    "QgsRuleBasedRendererV2": "QgsRuleBasedRenderer",
    "QgsRuleBasedRendererV2Count": "QgsRuleBasedRendererCount",
    "QgsRuleBasedRendererV2Model": "QgsRuleBasedRendererModel",
    "QgsRuleBasedRendererV2Widget": "QgsRuleBasedRendererWidget",
    "QgsScaleBarStyle": "QgsScaleBarRenderer",
    "QgsShapeburstFillSymbolLayerV2": "QgsShapeburstFillSymbolLayer",
    "QgsShapeburstFillSymbolLayerV2Widget": "QgsShapeburstFillSymbolLayerWidget",
    "QgsSimpleFillSymbolLayerV2": "QgsSimpleFillSymbolLayer",
    "QgsSimpleFillSymbolLayerV2Widget": "QgsSimpleFillSymbolLayerWidget",
    "QgsSimpleLineSymbolLayerV2": "QgsSimpleLineSymbolLayer",
    "QgsSimpleLineSymbolLayerV2Widget": "QgsSimpleLineSymbolLayerWidget",
    "QgsSimpleMarkerSymbolLayerV2": "QgsSimpleMarkerSymbolLayer",
    "QgsSimpleMarkerSymbolLayerV2Widget": "QgsSimpleMarkerSymbolLayerWidget",
    "QgsSingleBoxScaleBarStyle": "QgsSingleBoxScaleBarRenderer",
    "QgsSingleSymbolRendererV2": "QgsSingleSymbolRenderer",
    "QgsSingleSymbolRendererV2Widget": "QgsSingleSymbolRendererWidget",
    "QgsStyleV2": "QgsStyle",
    "QgsStyleV2ExportImportDialog": "QgsStyleExportImportDialog",
    "QgsStyleV2ExportImportDialogBase": "QgsStyleExportImportDialogBase",
    "QgsStyleV2GroupSelectionDialog": "QgsStyleGroupSelectionDialog",
    "QgsStyleV2ManagerDialog": "QgsStyleManagerDialog",
    "QgsStyleV2ManagerDialogBase": "QgsStyleManagerDialogBase",
    "QgsSurfaceV2": "QgsSurface",
    "QgsSvgMarkerSymbolLayerV2": "QgsSvgMarkerSymbolLayer",
    "QgsSvgMarkerSymbolLayerV2Widget": "QgsSvgMarkerSymbolLayerWidget",
    "QgsSymbolLayerV2": "QgsSymbolLayer",
    "QgsSymbolLayerV2AbstractMetadata": "QgsSymbolLayerAbstractMetadata",
    "QgsSymbolLayerV2Metadata": "QgsSymbolLayerMetadata",
    "QgsSymbolLayerV2Registry": "QgsSymbolLayerRegistry",
    "QgsSymbolLayerV2Utils": "QgsSymbolLayerUtils",
    "QgsSymbolLayerV2Widget": "QgsSymbolLayerWidget",
    "QgsSymbolLevelsV2Dialog": "QgsSymbolLevelsDialog",
    "QgsSymbolV2": "QgsSymbol",
    "QgsSymbolV2LegendNode": "QgsSymbolLegendNode",
    "QgsSymbolV2LevelItem": "QgsSymbolLevelItem",
    "QgsSymbolV2RenderContext": "QgsSymbolRenderContext",
    "QgsSymbolV2SelectorDialog": "QgsSymbolSelectorDialog",
    "QgsSymbolV2SelectorWidget": "QgsSymbolSelectorWidget",
    "QgsTicksScaleBarStyle": "QgsTicksScaleBarRenderer",
    "QgsTINInterpolator": "QgsTinInterpolator",
    "QgsUserInputDockWidget": "QgsUserInputWidget",
    "QgsVectorColorBrewerColorRampV2": "QgsColorBrewerColorRamp",
    "QgsVectorColorBrewerColorRampV2Dialog": "QgsColorBrewerColorRampDialog",
    "QgsVectorColorBrewerColorRampV2DialogBase": "QgsColorBrewerColorRampDialogBase",
    "QgsVectorColorRampV2": "QgsColorRamp",
    "QgsVectorColorRampV2Map": "QgsVectorColorRampMap",
    "QgsVectorGradientColorRampV2": "QgsGradientColorRamp",
    "QgsVectorGradientColorRampV2Dialog": "QgsGradientColorRampDialog",
    "QgsVectorGradientColorRampV2DialogBase": "QgsGradientColorRampDialogBase",
    "QgsVectorGradientRampV2": "QgsVectorGradientRamp",
    "QgsVectorJoinInfo": "QgsVectorLayerJoinInfo",
    "QgsVectorLayerImport": "QgsVectorLayerExporter",
    "QgsVectorLayersetRendererV2": "QgsVectorLayersetRenderer",
    "QgsVectorRandomColorRampV2": "QgsLimitedRandomColorRamp",
    "QgsVectorRandomColorRampV2Dialog": "QgsLimitedRandomColorRampDialog",
    "QgsVectorRandomColorRampV2DialogBase": "QgsLimitedRandomColorRampDialogBase",
    "vertexData": "QgsInterpolatorVertexData",
    "SymbolV2LegacyRuleKeyRole": "SymbolLegacyRuleKeyRole",
    "EditorWidgetV2": "EditorWidget",
    "mapPositionFixed": "hasFixedMapPosition",
    "defaultStyleV2Path": "defaultStylePath",
    "userStyleV2Path": "userStylePath",
    "selectedFeaturesIds": "selectedFeatureIds",
    "capitaliseLayerName": "capitalizeLayerName  <!--#spellok-->",
    "createSymbolLayerV2ListFromSld": "createSymbolLayerListFromSld",
    "editorWidgetV2Config": "editorWidgetConfig",
    "editorWidgetV2Text": "editorWidgetText",
    "editorWidgetV2Type": "editorWidgetType",
    "deleteVertexV2": "deleteVertex",
    "rendererV2": "renderer",
    "selectedFeaturesIds": "selectedFeatureIds",
    "deleteVertexV2": "deleteVertex",
    "capabiblitiesCache": "capabilitiesCache",
    "property": "cost",
    "properties": "strategies",
    "outArc": "outEdges",
    "inArc": "inEdges",
    "addArc": "addEdges",
    "arcCount": "edgeCount",
    "arc": "edge",
    "addArc": "addEdge",
    "addArc": "addEdge",
    "addProperter": "addStrategy",
    "getHeader": "header",
    "addProperter": "addStrategy",
    "QgsAnnotationItem": "==Removed== was removed. This was replaced by QgsAnnotation and QgsMapCanvasAnnotationItem.",
    "QgsAttributeAction": "==Removed== was removed, and replaced by QgsActionManager.",
    "QgsAttributeEditor": "==Removed== was removed. Use QgsEditorWidgetRegistry::create() instead.",
    "Bezier3D": "==Removed== ",
    "CloughTocherInterpolator": "==Removed== ",
    "QgsColorbutton": "==Removed== was removed. QgsColorButtonV2 has now been renamed to QgsColorButton. Hence, QgsColorButtonV2 does not exist anymore.",
    "QgsColorDialog": "==Removed== was removed, and QgsColorDialogV2 was renamed to QgsColorDialog. Hence, QgsColorButtonV2 does not exist anymore.",
    "QgsColorRampComboBox": "==Removed== was removed, replaced by QgsColorRampButton",
    "QgsCRSCache": "==Removed== was removed. QgsCoordinateReferenceSystem now internally uses a cache for CRS creation,",
    "QgsCoordinateTransformCache": "==Removed== was removed. QgsCoordinateTransform now transparently caches transforms.",
    "QgsDataDefined": "==Removed== was removed. Use the QgsProperty framework instead.",
    "QgsDataDefinedButton": "==Removed== was removed. Use QgsPropertyOverrideButton instead.",
    "QgsDataDefinedSymbolDialog": "==Removed== was removed. Code using this dialog should be reworked to use QgsPropertyOverrideButton",
    "QgsDatumTransformStore": "==Removed==  Use QgsCoordinateTransformContext instead.",
    "QgsDefaultPluginLayerLegend": "==Removed== was removed. Use QgsMapLayer::setLegend() to provide legend nodes for plugin layers.",
    "DualEdgeTriangulation": "==Removed== ",
    "QgsFileNameWidgetWrapper": "==Removed== was removed. Use QgsExternalResourceWidgetWrapper instead.",
    "QgsFileDropEdit": "==Removed== was removed. Use QgsFileWidget instead.",
    "QgsFormAnnotationItem": "==Removed==  Use QgsFormAnnotation instead.",
    "QgsGeometryAnalyzer": "==Removed==  Use the equivalent Processing algorithms instead.",
    "HalfEdge": "==Removed== ",
    "QgsHtmlAnnotationItem": "==Removed==  Use QgsHtmlAnnotation instead.",
    "QgsHttpTransaction": "==Removed==  This class was outdated and code should be ported to native Qt or Python implementations.",
    "QgsInterruptionChecker": "==Removed==  Use QgsFeedback instead.",
    "QgsGenericProjectionSelector": "==Removed==  Use QgsProjectionSelectionTreeWidget instead.",
    "QgsGeometryCache": "==Removed==  It got redundant after removal of old snapping classes (QgsSnapper + friends).",
    "QgsLabel": "==Removed== and QgsLabelAttributes. Replaced by labeling based on PAL library, see QgsLabelingEngine.",
    "QgsLabelingEngineInterface": "==Removed==  Replaced by QgsLabelingEngine.",
    "QgsLegendInterface": "==Removed== was removed. It was replaced by layer tree API (QgsLayerTreeNode class and others).",
    "QgsLegendModel": "==Removed== was removed.",
    "Line3D": "==Removed== ",
    "LinTriangleInterpolator": "==Removed== ",
    "QgsMapCanvasLayer": "==Removed==  Map canvas and overview canvas are updated separately with their own setLayers() calls.",
    "QgsMapCanvasMap": "==Removed==  It is an internal class used by map canvas.",
    "QgsMapLayerRegistry": "==Removed==  Its functionality has been moved to QgsProject.",
    "QgsMapRenderer": "==Removed==  It has been replaced by QgsMapRendererJob with subclasses and QgsMapSettings.",
    "QgsMapToolTouch": "==Removed==  The touch navigation functionality is now built into the standard QgsMapToolPan tool.",
    "Node": "==Removed== ",
    "NormVecDecorator": "==Removed== ",
    "ParametericLine": "==Removed== ",
    "QgsPhotoWidgetWrapper": "==Removed== was removed. Use QgsExternalResourceWidgetWrapper instead.",
    "QgsPointSample": "==Removed==  Use the Processing 'Random Points in Polygon' algorithm instead.",
    "QgsPseudoColorShader": "==Removed==  This shader has been broken for some time and was replaced by QgsSingleBandPseudoColorRenderer.",
    "QgsProjectBadLayerGuiHandler": "==Removed== was removed. It was unused in QGIS code and barely useful. Implement your own QgsProjectBadLayerHandler subclass if needed.",
    "QgsRendererV2DataDefinedMenus": "==Removed== was removed. Use QgsPropertyOverrideButton instead.",
    "QgsSizeScaleWidget": "==Removed==  Use QgsPropertyAssistantWidget instead.",
    "QgsLegacyHelpers": "==Removed== ",
    "QgsProjectionSelector": "==Removed==  Use QgsProjectionSelectionDialog instead.",
    "QgsProviderCountCalcEvent": "==Removed== and QgsProviderExtentCalcEvent. These classes were unused in QGIS core and unmaintained.",
    "QgsWebviewWidgetWrapper": "==Removed== was removed. Use QgsExternalResourceWidgetWrapper instead.",
    "QgsEditorWidgetConfig": "==Removed== was removed. Use QVariantMap instead.",
    "QgsScaleExpression": "==Removed==  Use QgsProperty with a QgsSizeScalePropertyTransformer instead.",
    "QgsSvgAnnotationItem": "==Removed==  Use QgsSvgAnnotation instead.",
    "QgsSvgCacheEntry": "==Removed==  This is an internal class and is no longer exposed to public API.",
    "QgsSymbologyV2Conversion": "==Removed== was removed. Reading of renderers from pre-1.0 versions is not supported anymore.",
    "QgsTextAnnotationItem": "==Removed==  Use QgsTextAnnotation instead.",
    "QgsTransectSample": "==Removed==  This class was unused and unmaintained.",
    "TriangleInterpolator": "==Removed== ",
    "Triangulation": "==Removed== ",
    "TriDecorator": "==Removed== ",
    "QgsSnapper": "==Removed==  Use QgsSnappingUtils instead.",
    "QgsSnappingResult": "==Removed==  Use QgsSnappingUtils instead.",
    "QgsMapCanvasSnapper": "==Removed==  Use QgsMapCanvas::snappingUtils() instead.",
    "Vector3D": "==Removed== ",
    "permissiveToDouble": "and permissiveToInt() where moved out of the QGis class and renamed to qgsPermissiveToDouble() and",
    "singleType": "has been removed. Use the equivalent QgsWkbTypes::singleType() instead",
    "multiType": "has been removed. Use the equivalent QgsWkbTypes::multiType() instead",
    "flatType": "has been removed. Use the equivalent QgsWkbTypes::flatType() instead",
    "isSingleType": "has been removed. Use the equivalent QgsWkbTypes::isSingleType() instead",
    "isMultiType": "has been removed. Use the equivalent QgsWkbTypes::isMultiType() instead",
    "wkbDimensions": "has been removed. Use the equivalent QgsWkbTypes::coordDimensions() instead",
    "fromOldWkbType": "has been removed. This is no longer required.",
    "fromNewWkbType": "has been removed. This is no longer required.",
    "vectorGeometryType": "has been removed. Use the equivalent QgsWkbTypes::geometryDisplayString() instead.",
    "featureType": "has been removed. Use the equivalent QgsWkbTypes::displayString() instead.",
    "fileMenu": "has been removed, use projectMenu() instead.",
    "getColumns": "was renamed to columns()",
    "getSquareSize": "was renamed to squareSize()",
    "updateFont": "was renamed to setFont()",
    "updateSize": "was renamed to setFontSize()",
    "updateStyle": "was renamed to setFontStyle()",
    "updateColumns": "was renamed to setColumns()",
    "asWkb": "returns QByteArray instead of new raw pointer",
    "wkbSize": "has been removed, use asWkb() to get length of returned QByteArray",
    "fromWkb": "gets the WKB pointer passed by reference instead of value, so that caller may to find out where the parsing ended",
    "asGML2": "was renamed to asGml2()",
    "asGML3": "was renamed to asGml3()",
    "asJSON": "was renamed to asJson()",
    "closestSegment": "now returns an integer value for the leftOf test (-1 if point is to the left",
    "doAction": "no longer accepts a substitution map. Use expression context",
    "expandAction": "has been removed. Use",
    "setPythonExecute": "was removed. Initialize `QgsPythonRunner` instead.",
    "canvasPressEvent": ", canvasReleaseEvent(), canvasMoveEvent() were removed. Handling of events is done in QgsMapToolAdvancedDigitizing.",
    "snappingMode": "was removed. Advanced digitizing now always uses project's snapping configuration.",
    "lineCircleIntersection": "was removed",
    "qgisMasterDbFilePath": "was renamed to qgisMasterDatabaseFilePath()",
    "qgisMasterDatabaseFilePath": "was renamed to qgisUserDatabaseFilePath()",
    "qgisAuthDbFilePath": "was renamed to qgisAuthDatabaseFilePath()",
    "srsDbFilePath": "was renamed to srsDatabaseFilePath()",
    "setAuthDbDirPath": "was renamed to setAuthDatabaseDirPath()",
    "createDB": "was renamed to createDatabase()",
    "composerTemplatePaths": "was renamed to layoutTemplatePaths()",
    "dialog": "was removed - just use the object directly.",
    "setIsAddDialog": "was removed. Use setMode() instead.",
    "setIsAddDialog": "was removed. Use setMode() instead.",
    "accept": "was removed. Use save() instead.",
    "reject": "was removed. Use resetValues() instead.",
    "hasConfigID": "has been renamed to hasConfigId()",
    "instance": "was removed in favor of QgsApplication::authManager() that returns an instance of the Auth Manager",
    "authDbConnection": "was renamed to authDatabaseConnection()",
    "authDbConfigTable": "was renamed to authDatabaseConfigTable()",
    "authDbServersTable": "was renamed to authDatabaseServersTable()",
    "authenticationDbPath": "was renamed to authenticationDatabasePath()",
    "masterPasswordHashInDb": "was renamed to masterPasswordHashInDatabase()",
    "scheduledAuthDbErase": "was renamed to scheduledAuthDatabaseErase()",
    "setScheduledAuthDbErase": "was renamed to setScheduledAuthDatabaseErase()",
    "setScheduledAuthDbEraseRequestEmitted": "was renamed to setScheduledAuthDatabaseEraseRequestEmitted()",
    "getAuthSetting": "was renamed to authSetting()",
    "getCertIdentity": "was renamed to certIdentity()",
    "getCertIdentityBundle": "was renamed to certIdentityBundle()",
    "getCertIdentityBundleToPem": "was renamed to certIdentityBundleToPem()",
    "getCertIdentities": "was renamed to certIdentities()",
    "getCertIdentityIds": "was renamed to certIdentityIds()",
    "getSslCertCustomConfig": "was renamed to sslCertCustomConfig()",
    "getSslCertCustomConfigByHost": "was renamed to sslCertCustomConfigByHost()",
    "getSslCertCustomConfigs": "was renamed to sslCertCustomConfigs()",
    "getIgnoredSslErrorCache": "was renamed to ignoredSslErrorCache()",
    "getCertAuthority": "was renamed to certAuthority()",
    "getSystemRootCAs": "was renamed to systemRootCAs()",
    "getExtraFileCAs": "was renamed to extraFileCAs()",
    "getDatabaseCAs": "was renamed to databaseCAs()",
    "getMappedDatabaseCAs": "was renamed to mappedDatabaseCAs()",
    "getCaCertsCache": "was renamed to caCertsCache()",
    "getCertTrustPolicy": "was renamed to certTrustPolicy()",
    "getCertificateTrustPolicy": "was renamed to certificateTrustPolicy()",
    "getCertTrustCache": "was renamed to certTrustCache()",
    "getTrustedCaCerts": "was renamed to trustedCaCerts()",
    "getUntrustedCaCerts": "was renamed to untrustedCaCerts()",
    "getTrustedCaCertsCache": "was renamed to trustedCaCertsCache()",
    "getTrustedCaCertsPemText": "was renamed to trustedCaCertsPemText()",
    "setInvertedColorRamp": "and invertedColorRamp() functions are gone, QgsColorRamp now responsible for invert",
    "createRenderer": "and updateColorRamp()'s inverted parameter is gone",
    "sizeScaleFieldChanged": "and scaleMethodChanged() were removed. These settings are no longer exposed in the widget's GUI.",
    "getColorRamp": "was removed.",
    "setAllowAlpha": "and allowAlpha() were removed. Use setAllowOpacity() and allowOpacity() instead.",
    "acceptLiveUpdates": "and setAcceptLiveUpdates() were removed. This functionality is no longer supported.",
    "setAllowAlpha": "was removed. Use setAllowOpacity() instead.",
    "getLiveColor": "was removed. This functionality is no longer supported.",
    "maximumColorCacheSize": "and setMaximumColorCacheSize() were no longer used and are removed.",
    "setAllowAlpha": "was removed. Use setAllowOpacity() instead.",
    "readXml": "and writeXml() require a new argument: a reference to QgsReadWriteContext",
    "readXml": "and writeXml() require a new argument: a reference to QgsReadWriteContext",
    "setCustomSrsValidation": "has been renamed to setCustomCrsValidation()",
    "saveAsUserCRS": "has been renamed to saveAsUserCrs()",
    "geographicCRSAuthId": "has been renamed to geographicCrsAuthId()",
    "geographicFlag": "was renamed to isGeographic()",
    "axisInverted": "was renamed to hasAxisInverted()",
    "syncDb": "was renamed to syncDatabase()",
    "sourceCrs": "and destCrs() now return a copy instead of a reference to the CRS. This has no effect on PyQGIS code, but c++",
    "isInitialised": "has been renamed to isValid()  <!--#spellok-->",
    "setDestCRS": "has been renamed to setDestinationCrs() for consistency",
    "destCRS": "has been renamed to destinationCrs() for consistency",
    "readXML": "and writeXML() have been removed.",
    "initialize": "was removed, calls to this method can safely be omitted.",
    "datumTransformations": "was moved to QgsDatumTransform, and now returns a list of QgsDatumTransform.TransformPair instead of a list of lists.",
    "datumTransformString": "was moved to QgsDatumTransform and renamed to datumTransformToProj()",
    "datumTransformCrsInfo": "was moved to QgsDatumTransform and renamed to datumTransformInfo(), and now returns a QgsDatumTransform.TransformInfo object.",
    "sourceDatumTransform": "was renamed to sourceDatumTransformId()",
    "setSourceDatumTransform": "was renamed to setSourceDatumTransformId()",
    "destinationDatumTransform": "was renamed to destinationDatumTransformId()",
    "setDestinationDatumTransform": "was renamed to setDestinationDatumTransformId()",
    "transform": "now returns a QgsCoordinateTransform object, not a pointer. An invalid QgsCoordinateTransform will",
    "parseXML": "has been renamed to parseXml()",
    "expressionParams": ", setExpressionParams() and insertExpressionParam() have been removed.",
    "supportedCRS": "has been renamed to supportedCrs()",
    "isPopulated": "has been removed. Use state() instead.",
    "capabilities": "has been removed. Use capabilities2() instead (TODO: rename back to capabilities()).",
    "emitBeginInsertItems": ", emitEndInsertItems(), emitBeginRemoveItems(), emitEndRemoveItems(), emitDataChanged(), emitStateChanged() have been removed.",
    "actions": "now requires a new QWidget parent argument. Subclasses should ensure that returned items have been",
    "transformation": "now returns a QgsCoordinateTransform object, not a pointer. An invalid QgsCoordinateTransform will",
    "transformation": "also optional source and destination authid parameters",
    "referencedFields": "no longer takes a QgsFields argument.",
    "renderDiagram": "now takes an optional data defined overrides collection argument.",
    "readXml": ", _readXml(), writeXml(), _writeXml() do not take QgsVectorLayer as an argument anymore.",
    "readXml": ", _readXml(), writeXml(), _writeXml() require a new argument: a reference to QgsReadWriteContext",
    "sizeLegend": ", setSizeLegend(), sizeLegendSymbol() and setSizeLegendSymbol() have been replaced by dataDefinedSizeLegend() and setDataDefinedSizeLegend() methods in QgsLinearlyInterpolatedDiagramRenderer.",
    "coordinateTransform": "now returns a QgsCoordinateTransform object, not a pointer. An invalid QgsCoordinateTransform will",
    "setCoordinateTransform": "now takes a QgsCoordinateTransform object, not a pointer. Use an invalid QgsCoordinateTransform in",
    "referencedFields": "no longer requires a QgsFields argument.",
    "readXml": "and writeXml() do not take QgsVectorLayer as an argument anymore.",
    "readXml": "and writeXml() do not take QgsVectorLayer as an argument anymore.",
    "setEllipsoidalMode": "was removed. Ellipsoidal calculations are now enabled whenever a valid ellipsoid() has been set. Set the",
    "ellipsoidalEnabled": "was removed. Ellipsoidal calculations are now enabled whenever a valid ellipsoid() is set. Check",
    "sourceCrs": "now returns a QgsCoordinateReferenceSystem instead of the crs ID.",
    "setSourceCrs": "now requires a QgsCoordinateReferenceSystem instead of crs ID, and requires a QgsCoordinateTransformContext object. PyQGIS code",
    "setSourceAuthId": "was removed. Use setSourceCrs() instead.",
    "geographic": "was removed. Check sourceCrs().isGeographic() instead.",
    "measure": "has been removed. Use measureArea() or measureLength() instead.",
    "textUnit": "was removed. Use formatDistance() or formatArea() instead.",
    "writeSolid": "was removed. Use writePolygon() instead.",
    "writePoint": ", writeFilledCircle(), writeCircle(), writeText() and writeMText() now take QgsPointV2 arguments",
    "setMapUnits": "was removed. The map units are dictated by the units for the destination CRS.",
    "setSymbologyScaleDenominator": "and symbologyScaleDenominator() were renamed to setSymbologyScale() and symbologyScale()",
    "widgetType": "and widgetConfig() now reflect only the user configured values.",
    "widgetConfig": ", setWidgetType(), setWidgetConfig() and removeWidgetConfig() now only take a string as first parameter. Access by index has been removed.",
    "widgetType": "has been removed in favor of QgsVectorLayer::editorWidgetSetup()",
    "expression": ", setExpression(), expressionDescription() and setExpressionDescription()",
    "notNull": "and setNotNull() have been removed. Use QgsVectorLayer.setFieldConstraint()/fieldConstraints(), or QgsField.constraints() instead.",
    "readXml": "and writeXml() now also expect a reference to QgsReadWriteContext object.",
    "replaceExpressionText": "no longer accepts a substitution map parameter. Use expression context variables instead.",
    "helptext": "has been renamed to helpText()",
    "isValid": "has been renamed to checkExpression()",
    "acceptVisitor": "has been removed",
    "variableHelpText": "no longer returns a formatted HTML string. It now just returns the plain text help string. Use formatVariableHelp()",
    "projectScope": ", setProjectVariable() and setProjectVariables() require pointer to QgsProject as the first argument.",
    "geometryAndOwnership": "has been removed. Use geometry() instead.",
    "setGeometryAndOwnership": "has been removed. Use setGeometry() instead.",
    "fields": "no longer returns a pointer, but instead a QgsFields value.",
    "symbols": "has been removed. The symbols( QgsRenderContext& context ) method should be used instead (previously available as symbols2 in PyQGIS bindings).",
    "rotationField": "and setRotationField() were removed. Data defined properties for QgsSymbolLayer should be used instead.",
    "copyPaintEffect": "was removed. copyRendererData() should be used instead.",
    "usedAttributes": "now requires a QgsRenderContext argument.",
    "save": "expects QgsReadWriteContext reference as the last argument",
    "legendSymbologyItems": "was removed.",
    "legendSymbolItems": "was removed.",
    "legendSymbolItemsV2": "has been renamed to legendSymbolItems()",
    "isEmpty": "was renamed to isNull() to differentiate a missing geometry from a geometry which is empty (eg an",
    "wkbSize": "was removed. WKB representation is no longer cached within QgsGeometry",
    "asGeos": "has been replaced by exportToGeos(). GEOS representation is no longer cached within QgsGeometry",
    "avoidIntersections": "got an extra argument: list of layers to include in the operation (previously read from active QgsProject)",
    "isGeosEmpty": "was removed. Use isEmpty() instead.",
    "reshapeGeometry": "expects QgsLineString as a parameter instead of a list of 2D points (so that it can support 3D geometries)",
    "vertexAt": "now returns a QgsPoint (previously QgsPointV2) instead of a QgsPointXY (previously QgsPoint)",
    "fromPolyline": "now requires a list of QgsPoint objects, instead of QgsPointXY 2d points. A new method fromPolylineXY was",
    "fromPoint": "was renamed to fromPointXY()",
    "fromMultiPoint": "was renamed to fromMultiPointXY()",
    "fromMultiPolyline": "was renamed to fromMultiPolylineXY()",
    "fromPolygon": "was renamed to fromPolygonXY()",
    "fromMultiPolygon": "was renamed to fromMultiPolygonXY()",
    "exportToWkt": "was renamed to asWkt()",
    "exportToGeoJSON": "was renamed to asJson()",
    "closestSegmentWithContext": "now returns an extra value, indicating whether the point is to the left of the geometry",
    "equals": "now performs a fast, strict equality check, where geometries are considered equal only if they have the",
    "locateBetweenMeasures": "and locateAlongMeasure() now take geometry references, not pointers, and return",
    "centroid": "returns the point instead of working on a parameter. The return value is a `nullptr` when `false` has been returned in the past.",
    "pointOnSurface": "returns the point instead of working on a parameter. The return value is a `nullptr` when `false` has been returned in the past.",
    "splitGeometry": "now returns new geometries as QgsGeometry, instead of QgsAbstractGeometry",
    "combine": "now requires a list of QgsGeometry, instead of QgsAbstractGeometry",
    "simplifyGeometry": "has been removed and simplify() must be used instead .",
    "getDataValues": "has been removed - use QgsVectorLayerUtils::getDoubleValues() instead",
    "sizeScaleFieldChanged": "and scaleMethodChanged() were removed. These settings are no longer exposed in the widget's GUI.",
    "destinationCrs": "now returns a copy instead of a reference to the CRS. This has no effect on PyQGIS code, but c++",
    "outVertex": "was renamed as toVertex() (yes, the original name was the opposite of the returned value!)",
    "inVertex": "was renamed as fromVertex() (yes, the original name was the opposite of the returned value!)",
    "outEdges": "was renamed as incomingEdges() (yes, the original name was the opposite of the returned value!)",
    "inEdges": "was renamed as outgoingEdges() (yes, the original name was the opposite of the returned value!)",
    "cancelled": " and isCancelled() has been renamed to canceled() and isCanceled(), respectively  <!--#spellok-->",
    "setInvertedColorRamp": "and invertedColorRamp() functions are gone, QgsColorRamp now responsible for invert",
    "createRenderer": "and updateColorRamp()'s inverted parameter is gone",
    "writeFile": "now takes an optional QgsFeedback argument instead of using a QProgressDialog",
    "setInvertRamp": "and invertRamp() functions are gone, QgsColorRamp now responsible for invert",
    "selectedFeaturesIds": "has been renamed to selectedFeatureIds()",
    "sourceCrs": "now returns a copy instead of a reference to the CRS. This has no effect on PyQGIS code, but c++",
    "addDiagramLayer": "was removed. Use prepareDiagramLayer() instead.",
    "labelsAtPosition": "was removed. Use takeResults() and methods of QgsLabelingResults instead.",
    "labelsWithinRect": "was removed. Use takeResults() and methods of QgsLabelingResults.",
    "loadLayerDefinition": "now also requires QgsProject as the second argument",
    "loadLayerDefinition": "and exportLayerDefinition() variants that take QDomDocument as the first argument now expect QgsReadWriteContext as the last argument",
    "expressionContext": ", setExpressionContext(), setMapCanvas() and mapCanvas() have been removed in favor of setContext()/context()",
    "readChildrenFromXML": "has been renamed to readChildrenFromXml()",
    "isVisible": "is moved to QgsLayerTreeNode",
    "setVisible": "is replaced by QgsLayerTreeNode::setItemVisibilityChecked()",
    "readXml": "and readChildrenFromXml() do not resolve layers from the layer IDs anymore. Call resolveReferences() or use readXml() override with QgsProject as the second argument.",
    "setLayerName": ", layerName() were renamed to setName(), name()",
    "isVisible": "is moved to QgsLayerTreeNode",
    "setVisible": "is replaced by QgsLayerTreeNode::setItemVisibilityChecked()",
    "readXml": "does not resolve layer from the layer ID anymore. Call resolveReferences() or use readXml() override with QgsProject as the second argument.",
    "setAutoEnableCrsTransform": "and autoEnableCrsTransform() were removed. CRS transformation is now always enabled.",
    "setCanvasLayers": "now requires a third map layer list argument for storage of all layers in the layer tree order.",
    "setCustomLayerOrder": "has been removed. Use `QgsProject::layerTreeRoot().setCustomLayerOrder()` instead",
    "customLayerOrder": "has been removed. Use `QgsProject::layerTreeRoot().customLayerOrder()` instead",
    "hasCustomLayerOrder": "has been removed. Use `QgsProject::layerTreeRoot().hasCustomLayerOrder()` instead",
    "setHasCustomLayerOrder": "has been removed. Use `QgsProject::layerTreeRoot().setHasCustomLayerOrder()` instead",
    "defaultLayerOrder": "has been removed.",
    "legendFilterByMap": "was renamed to legendFilterMapSettings()",
    "isIndexSymbologyNode": "was removed. Use index2legendNode() instead.",
    "layerNodeForSymbologyNode": "was removed. Use index2legendNode()->parent() instead.",
    "refreshLayerSymbology": "was removed. Use refreshLayerLegend() instead.",
    "setAutoCollapseSymbologyNodes": "was removed. Use setAutoCollapseLegendNodes() instead.",
    "autoCollapseSymbologyNodes": "was removed. Use autoCollapseLegendNodes() instead.",
    "readCommonXML": "has been renamed to readCommonXml()",
    "writeCommonXML": "has been renamed to writeCommonXml()",
    "readXml": "does not resolve layers from the layer IDs anymore. Call resolveReferences() or use readXml() override with QgsProject as the second argument.",
    "setLayerSet": "has been replaced by setLayers() which accepts list of QgsMapLayer objects instead of QgsMapCanvasLayer objects",
    "rotationEnabled": "and enableRotation() have been removed, since map rotation is now always supported",
    "map": "has been removed because QgsMapCanvasMap is not available in API anymore.",
    "mapRenderer": "has been removed. Use directly map canvas methods to get/set configuration or mapSettings() (for reading only).",
    "canvasPaintDevice": "has been removed. Use map canvas items to draw anything on top of canvas.",
    "clear": "has been removed. Use refresh() instead.",
    "setCanvasColor": "and canvasColor() are not virtual methods anymore.",
    "updateFullExtent": "has been removed. No need to call it explicitly. Full extent calculation is done in QgsMapSettings.",
    "setDirty": "and isDirty() have been removed. Use refresh() to refresh canvas content.",
    "setWheelAction": "and WheelAction enum have been removed. Custom wheel actions are not supported anymore.",
    "updateMap": ", showError(), useImageToRender() have been removed. They did nothing since 2.4.",
    "setProgress": "signal has been removed. It was not emitted since 2.0.",
    "enableOverviewMode": "and updateOverview() have been removed. Map canvas does not keep pointer to overview canvas anymore. Use QgsLayerTreeMapCanvasBridge::setOverviewCanvas() to set up updates of overview canvas together with main canvas.",
    "setCrsTransformEnabled": ", hasCrsTransformEnabled(), hasCrsTransformEnabledChanged() were removed. CRS transformation is now always enabled.",
    "setMapUnits": "was removed. The map units are dictated by the units for the destination CRS.",
    "layerCrsChange": "slot was removed. Datum transforms are now handled in QgisApp.",
    "setPanningOffset": "was removed.",
    "crs": "now returns a QgsCoordinateReferenceSystem object, not a reference. This change has no effect for PyQGIS code.",
    "createMapRenderer": "has been made pure virtual.",
    "draw": "has been removed. Use createMapRenderer() method for rendering of layers.",
    "setLayerName": "was removed, use setName() instead. The layerNameChanged() signal has been replaced by nameChanged().",
    "toggleScaleBasedVisibility": "was replaced by setScaleBasedVisibility()",
    "lastErrorTitle": ", lastError(), cacheImage(), onCacheImageDelete(), clearCacheImage() and the signals drawingProgress(),",
    "extent": ", styleURI(), exportNamedStyle(), exportSldStyle(), writeXml(), metadata() were made const. This has no effect on PyQGIS code, but c++ code implementing derived layer classes will need to update the signatures of these methods to match.",
    "drawLabels": "method was removed. It used old deprecated labeling. Replaced by labeling based on PAL library, see QgsLabelingEngine.",
    "readLayerXML": "was renamed to readLayerXml()",
    "writeLayerXML": "was renamed to writeLayerXml()",
    "capitaliseLayerName": "was renamed to capitalizeLayerName() <!--#spellok-->",
    "asLayerDefinition": ", fromLayerDefinition(), fromLayerDefinitionFile() were moved to QgsLayerDefinition class and renamed to exportLayerDefinitionLayers() resp. loadLayerDefinitionLayers()",
    "loadNamedStyleFromDb": "was renamed to loadNamedStyleFromDatabase()",
    "readLayerXml": "and writeLayerXml() expect QgsReadWriteContext reference as the last argument",
    "readSymbology": "and writeSymbology() expect QgsReadWriteContext reference as the last argument",
    "readStyle": "and writeStyle() expect QgsReadWriteContext reference as the last argument",
    "readXml": "and writeXml() expect QgsReadWriteContext reference as the last argument",
    "metadata": "was renamed to htmlMetadata() in both QgsMapLayer and QgsRasterDataProvider",
    "setMaximumScale": "and setMinimumScale(), maximumScale() and minimumScale() had the opposite meaning to other min/max scales in the API, and their definitions have now been swapped. setMaximumScale",
    "capitalizeLayerName": "was removed. Use formatLayerName() instead.",
    "originalName": "was removed. Use name() instead.",
    "defaultPluginLegend": "was removed. Plugin layers have to provide their legend implementation.",
    "snapPoint": "does not take SnappingMode argument anymore. Snapping is done according to project's snapping configuration.",
    "snapSegment": "was removed.",
    "layerSet": "and setLayerSet() have been replaced by layers() and setLayers() which work with list of layers instead of layer IDs",
    "destinationSrsChanged": "was renamed to destinationCrsChanged()",
    "hasCrsTransformEnabled": "was removed. CRS transformation is now always enabled",
    "drawExtentRect": "and destinationCrsChanged() are now protected",
    "transformation": "now returns a QgsCoordinateTransform object, not a pointer. An invalid QgsCoordinateTransform will",
    "destinationSrsChanged": "was renamed to destinationCrsChanged()",
    "getCompositionMode": ", getBlendModeEnum() and BlendMode enum have been moved to QgsPainting utility class.",
    "reprojectToLayerExtent": "now takes a QgsCoordinateTransform reference, not a pointer. An invalid QgsCoordinateTransform should",
    "prepareJobs": "and drawLabeling() (neither available in PyQGIS) do not take QgsPalLabeling parameter anymore. All drawing of labels is done by QgsLabelingEngine.",
    "drawOldLabeling": ", drawNewLabeling() were removed. The method drawLabeling() should be used instead.",
    "setRequestedGeometryCacheForLayers": "was removed. There is no extra caching done during rendering job.",
    "renderComplete": "was removed. Map tools must not directly depend on rendering progress.",
    "isTransient": "and isEditTool() were removed. Use flags() instead.",
    "setMode": "was replaced by setAdvancedDigitizingAllowed() and setAutoSnapEnabled()",
    "mode": "and CaptureMode enum have been moved to QgsMapToolCapture subclass",
    "setYMaximum": ", setYMinimum(), setXMinimum() were removed. Use setParameters() instead",
    "simplifyGeometry": ", simplifyPoints(), isGeneralizableByMapBoundingBox(), _getLineString(), _getPolygon() methods have been removed.",
    "layers": "and setLayers() now work with list of layers instead of layer IDs",
    "layerTransform": "now returns a QgsCoordinateTransform object, not a pointer. An invalid QgsCoordinateTransform will",
    "destinationCrs": "now returns a copy instead of a reference to the CRS. This has no effect on PyQGIS code, but c++",
    "setCrsTransformEnabled": "and hasCrsTransformEnabled() were removed. CRS transformation is now always enabled.",
    "setMapUnits": "was removed. The map units are dictated by the units for the destination CRS.",
    "bounds": "is now pure virtual and must be implemented in all subclasses.",
    "sendGet": "was removed. Use get() directly.",
    "deleteReply": "was removed. Use abort() and deleteLayer() on the reply directly.",
    "requiredAttributes": "now returns a set of attributes, instead of a list",
    "selectedCrsId": "was removed. Use crs() instead.",
    "elemID": "has been renamed to elemId()",
    "setOutputDbFileName": "and outputDbFileName() have been renamed to setOutputDatabaseFileName()",
    "connectionInfo": "was removed.",
    "selectedLayersCRSs": "has been renamed selectedLayersCrses()",
    "populateCRS": "has been renamed to populateCrs()",
    "clearCRS": "has been renamed to clearCrs()",
    "addWMSListRow": "has been renamed to addWmsListRow()",
    "addWMSListItem": "has been renamed to addWmsListItem()",
    "selectedCRS": "has been renamed to selectedCrs()",
    "colors": "has been removed, use classes() instead.",
    "layer": "was removed. If direct access to QgsPalLayerSettings is necessary, use QgsPalLayerSettings::fromLayer()",
    "candidates": "was removed.",
    "addDiagramLayer": "was removed. Use prepareDiagramLayer() instead.",
    "labelsAtPosition": "was removed. Use takeResults() and methods of QgsLabelingResults instead.",
    "labelsWithinRect": "was removed. Use takeResults() and methods of QgsLabelingResults instead.",
    "isStoredWithProject": "and setStoredWithProject() had no effect and were removed.",
    "readFromLayer": "and writeToLayer() have been removed. Labeling is read/written in QgsAbstractVectorLayerLabeling and its subclasses.",
    "prepareGeometry": "and geometryRequiresPreparation() now take a QgsCoordinateTransform reference, not a pointer. An invalid QgsCoordinateTransform should be used instead of a null pointer if no transformation is required.",
    "dataDefinedProperty": ", setDataDefinedProperty(), removeDataDefinedProperty(),",
    "readXml": "and writeXml() now expect a reference to QgsReadWriteContext.",
    "fromLayer": "has been reoved. Labeling is read/written in QgsAbstractVectorLayerLabeling and its subclasses.",
    "addMainPanel": "has been renamed to setMainPanel()",
    "mainWidget": "has been renamed to mainPanel()",
    "takeMainWidget": "has been renamed to takeMainPanel()",
    "createMapRenderer": ": default implementation (which called plugin's draw() method) has been removed. Plugin layers must implement createMapRenderer().",
    "clone": ": new pure virtual method. Plugin layer must implement clone().",
    "legendSymbologyItems": "has been removed. Use QgsMapLayer::setLegend() to provide legend nodes.",
    "onSegment": "has been removed. Use sqrDistToSegment() instead for a more precise test.",
    "toDegreesMinutesSeconds": "and toDegreesMinutes() have been removed. Use QgsCoordinateFormatter instead.",
    "wellKnownText": "was renamed to asWkt()",
    "setMaxLabelScaleDenominator": "and maxLabelScaleDenominator() were renamed to setMinimumLabelScale() and",
    "destCRS": "has been renamed to destinationCrs()",
    "destinationCrs": "now returns a copy instead of a reference to the CRS. This has no effect on PyQGIS code, but c++",
    "visibilityPresetCollection": "has been renamed to mapThemeCollection()",
    "clearProperties": "was removed. Use clear() instead.",
    "createEmbeddedLayer": "does not take vectorLayerList as the third parameter anymore.",
    "writePath": "does not accept second argument (relativeBasePath) anymore. Use QgsPathResolver instead.",
    "dialog": "has been removed",
    "setMessage": "has been added to set message on inner dialog.",
    "provider": "was renamed to createProvider()",
    "selectWidget": "was renamed to createSelectionWidget()",
    "providerLibrary": "was renamed to createProviderLibrary()",
    "processCalculation": "now uses an optional QgsFeedback instead of QProgressDialog",
    "srcDataType": "has been renamed to sourceDataType()",
    "srcHasNoDataValue": "has been renamed to sourceHasNoDataValue()",
    "useSrcNoDataValue": "has been renamed to useSourceNoDataValue()",
    "setUseSrcNoDataValue": "has been renamed to setUseSourceNoDataValue()",
    "srcNoDataValue": "has been renamed to sourceNoDataValue()",
    "metadata": "was renamed to htmlMetadata()",
    "draw": "has been removed from the interface as it was not used anywhere.",
    "metadata": "was renamed to htmlMetadata()",
    "makeTableCell": "has been removed",
    "makeTableCells": "has been removed, look for the new class QgsHtmlUtils",
    "alpha": "and setAlpha() were removed. Use opacity() and setOpacity() instead.",
    "srcDataType": "has been renamed to sourceDataType()",
    "srcInput": "has been renamed to sourceInput()",
    "block": "has new 'feedback' argument.",
    "setDrawingStyle": "was removed. Use setRendererForDrawingStyle() or setRenderer() instead.",
    "previewAsPixmap": "was removed. Use previewAsImage() instead.",
    "updateProgress": "had no effect and was removed.",
    "showProgress": "and onProgress() were removed",
    "extentSize": "now takes a QgsCoordinateTransform reference, not a pointer. An invalid QgsCoordinateTransform should be used instead of a null pointer if no transformation is required.",
    "displayBandName": "was removed.",
    "createFromXML": "has been renamed to `QgsRelation::createFromXml()`",
    "setRelationName": "has been renamed to `QgsRelation::setName()`",
    "setRelationId": "has been renamed to `QgsRelation::setId()`",
    "processRaster": "now uses a QgsFeedback object instead of a QProgressDialog",
    "setMapRenderer": "has been removed. Use setMapSettings() instead.",
    "excludeAttributesWMS": "and setExcludeAttributesWMS() have been renamed to excludeAttributesWms() and",
    "excludeAttributesWFS": "and setExcludeAttributesWFS() have been renamed to excludeAttributesWfs() and",
    "editorWidgetV2": "and editorWidgetV2Config() have been removed and QgsEditorWidgetRegistry::findBest() must be used instead.",
    "setEditorWidgetV2": ", setEditorWidgetV2Config() have been removed and their equivalent in editFormConfig() must be used instead.",
    "setCheckedState": "is removed. Use `editFormConfig()->setWidgetConfig()` instead.",
    "valueMap": ", valueRelation(), dateFormat(), widgetSize() have been removed. Use QgsEditorWidgetRegistry::findBest().config() instead.",
    "coordinateTransform": "now returns a QgsCoordinateTransform object, not a pointer. An invalid QgsCoordinateTransform will",
    "setCoordinateTransform": "now takes a QgsCoordinateTransform reference, not a pointer. An invalid QgsCoordinateTransform should be used instead of a null pointer if no transformation is required.",
    "rasterScaleFactor": "and setRasterScaleFactor() were removed. In QGIS 3.0 QPainter destinations should always be constructed so that 1 painter unit = 1 pixel.",
    "expressionContext": ", setExpressionContext(), setMapCanvas() and mapCanvas() have been removed in favor of setContext()/context()",
    "expressionContext": ", setExpressionContext(), setMapCanvas() and mapCanvas() have been removed in favor of setContext()/context()",
    "setHeader": "was renamed to setResponseHeader()",
    "removeHeader": "was renamed to removeResponseHeader()",
    "setToGeometry": "and addGeometry() now take geometry references, not pointers.",
    "refineRuleCategoriesGui": "and refineRuleRangesGui() no longer take a QModelIndexList argument.",
    "minimumScaleDenom": "and maximumScaleDenom() were removed. Now minimumScale() and maximumScale() report the scale denominator.",
    "name": "and setName() have been removed. Use shape() and setShape() instead.",
    "prepareShape": "and preparePath() were removed. Calling these methods manually should no longer be required.",
    "setName": "was removed.",
    "classificationMinMaxOrigin": "and setClassificationMinMaxOrigin() removed. Use minMaxOrigin() and setMinMaxOrigin()",
    "sizeScaleFieldChanged": "and scaleMethodChanged() were removed. These settings are no longer exposed in the widget's GUI.",
    "changeSingleSymbol": "and showSymbolLevels() slots were made private.",
    "populateLayerTable": "now takes a list of QgsSublayersDialog.LayerDefinition values",
    "selectionNames": "and selectionIndexes() were removed. Use selection().",
    "containsParamsV2": "was removed. Use containsParamsV3() instead.",
    "svgAsImage": ", svgAsPicture(), svgViewboxSize(), svgContent(), insertSvg(), cacheEntry() only accept absolute path to SVG file (relative paths will not be resolved).",
    "create": "has been removed - use ordinary constructor instead.",
    "currentSvgPathToName": "has been removed - absolute paths are always used.",
    "groupsTreeView": ", imagesListView(), filePathLineEdit(), filePathButton(), relativePathCheckbox(), selectorLayout() have been removed as they were leaking implementation details.",
    "layout": ", buttonBox() has been removed as they were leaking implementation details.",
    "startRender": "now accepts a QgsFields reference, not a pointer.",
    "isSymbolLayerCompatible": "was removed. Use QgsSymbolLayer::isCompatibleWithSymbol() instead.",
    "setRenderHints": "and renderHints() now accept and return a QgsSymbol::RenderHints flag rather",
    "usedAttributes": "now requires a QgsRenderContext argument.",
    "setDataDefinedAngle": ", dataDefinedAngle(), setDataDefinedSize(), dataDefinedSize(), setDataDefinedWidth() and dataDefinedWidth()",
    "alpha": "and setAlpha() were removed. Use opacity() and setOpacity() instead.",
    "removeDataDefinedProperty": ", removeDataDefinedProperties(), hasDataDefinedProperties(), hasDataDefinedProperty(), evaluateDataDefinedProperty()",
    "getDataDefinedProperty": "was removed. Use dataDefinedProperties() instead.",
    "expression": "was removed.",
    "usedAttributes": "now requires a QgsRenderContext argument",
    "saveDataDefinedProperties": "was removed. This is no longer required.",
    "restoreDataDefinedProperties": "was renamed to restoreOldDataDefinedProperties()",
    "estimateMaxBleed": "now requires a QgsRenderContext argument (since the bleed depends on render context for non-pixel units)",
    "expressionContext": ", setExpressionContext(), setMapCanvas() and mapCanvas() have been removed in favor of setContext()/context()",
    "fields": "now returns a QgsFields value, not a pointer.",
    "alpha": "and setAlpha() were removed. Use opacity() and setOpacity() instead.",
    "encodeOutputUnit": "and decodeOutputUnit() were removed. QgsUnitTypes::encodeUnit() and QgsUnitTypes::decodeRenderUnit() should be used instead.",
    "createRenderContext": "was moved to QgsRenderContext::fromQPainter()",
    "lineWidthScaleFactor": "and convertToPainterUnits() were moved to QgsRenderContext::convertToPainterUnits()",
    "convertToMapUnits": "was moved to QgsRenderContext::convertToMapUnits()",
    "convertFromMapUnits": "was moved to QgsRenderContext::convertFromMapUnits()",
    "pixelSizeScaleFactor": "was removed. Use QgsRenderContext::convertToPainterUnits() instead.",
    "mapUnitScaleFactor": "was removed. Use QgsRenderContext::convertToMapUnits() instead.",
    "estimateMaxSymbolBleed": "now requires a QgsRenderContext argument (since the bleed depends on render context for non-pixel units)",
    "loadSymbol": ", saveSymbol(), loadSymbols(), saveSymbols(), loadSymbolLayer() now require a reference to QgsReadWriteContext",
    "symbolNameToPath": "and symbolPathToName() have been renamed to svgSymbolNameToPath() and svgSymbolPathToName() and they require reference to QgsPathResolver",
    "saveSymbol": "was removed.",
    "saveSymbol": "was removed.",
    "expressionContext": ", setExpressionContext(), setMapCanvas() and mapCanvas() have been removed in favor of setContext()/context()",
    "expressionContext": ", setExpressionContext(), setMapCanvas() and mapCanvas() have been removed in favor of setContext()/context()",
    "setExportTriangulationToFile": "and setTriangulationFilePath() were removed. Use setTriangulationSink() instead.",
    "vertexSearchRadius": ", defaultTolerance(), toleranceInMapUnits() do not have variant with QgsMapRenderer anymore. Use the variants with QgsMapSettings.",
    "hasCrsTransformEnabled": "and setCrsTransformEnabled() were removed. CRS transformation is now always enabled when required.",
    "setDestinationCrs": "now requires a QgsCoordinateTransformContext argument.",
    "createTransaction": "takes a set of map layers instead of a layer ids",
    "normal": "was removed. Use normalized() instead.",
    "capabilities": "now returns a typesafe QgsVectorDataProvider::Capabilities object, not an integer.",
    "convertToProviderType": "now takes a geometry reference, not a pointer.",
    "geometryType": "has been renamed to wkbType() to be in line with QgsVectorLayer",
    "isSaveAndLoadStyleToDBSupported": "was renamed to isSaveAndLoadStyleToDatabaseSupported()",
    "excludeAttributesWMS": "and setExcludeAttributesWMS() have been renamed to excludeAttributesWms() and",
    "excludeAttributesWFS": "and setExcludeAttributesWFS() have been renamed to excludeAttributesWfs() and",
    "changeGeometry": "now accepts a geometry reference, not a pointer.",
    "addTopologicalPoints": "now takes a geometry reference, not a pointer.",
    "commitErrors": "now returns an object, rather than a reference. This has no effect on PyQGIS code.",
    "subsetString": "was made const. This has no effect on PyQGIS code, but c++ code implementing derived layer classes will need to update the signature of this method to match.",
    "label": ", enableLabels(), hasLabelsEnabled(), drawLabels() have been removed. Replaced by labeling based on PAL library, see QgsLabelingEngine.",
    "select": "replaced by selectByRect()",
    "selectedFeaturesIds": "replaced by selectedFeatureIds()",
    "selectedFeaturesIterator": "was replaced by getSelectedFeatures()",
    "setSelectedFeatures": "replaced by selectByIds()",
    "applyNamedStyle": "replaced by importNamedStyle()",
    "isReadOnly": "use readOnly()",
    "editFormConfig": "returns a copy instead of direct access (Use setEditFormConfig to update)",
    "saveStyleToDatabase": ": msgError argument is correctly declared as output argument",
    "getStyleFromDatabase": ": msgError argument is correctly declared as output argument",
    "loadNamedStyle": ": theResultFlag argument is correctly declared as output argument",
    "featureCount": "now requires a legend key string instead of a QgsSymbol pointer argument.",
    "createJoinCaches": "has been removed. Caches are created/updated when needed internally.",
    "checkJoinLayerRemove": "has been removed. Joins are removed internally when joined layer is deleted.",
    "readXml": "does not resolve references to joined layers. Call resolveReferences() when joined layers are available.",
    "snapWithContext": ", snapToGeometry() - last argument has changed from QgsSnapper::SnappingType to QgsSnappingResult::SnappingType (no change in functionality).",
    "snapPoint": "has been removed - use QgsPointLocator class instead.",
    "snapWithContext": "has been removed - use QgsPointLocator class instead.",
    "insertSegmentVerticesForSnap": "has been removed - use addTopologicalPoints() directly.",
    "addFeature": "no longer accepts an alsoUpdateExtent boolean - this extra argument has been ignored for some time",
    "addFeatures": "no longer accepts a makeSelected boolean, and will not automatically select newly added features. If desired, features must be manually selected by calling selectByIds() after addFeatures()",
    "annotationForm": "and setAnnotationForm() have been removed. Form path is stored in individual QgsFormAnnotation objects.",
    "hasGeometryType": "has been removed, replaced by QgsMapLayer::isSpatial()",
    "addRing": "now returns QgsGeometry::OperationResult enum, integer representation of returned values may have changed",
    "addPart": "now returns QgsGeometry::OperationResult enum, integer representation of returned values may have changed",
    "splitParts": "now returns QgsGeometry::OperationResult enum, integer representation of returned values may have changed",
    "splitFeatured": "now returns QgsGeometry::OperationResult enum, integer representation of returned values may have changed",
    "pendingFields": "was dropped. Use fields() instead.",
    "pendingAllAttributesList": "was dropped. Use allAttributes() instead.",
    "pendingPkAttributesList": "and pkAttributeList() were dropped. Use primaryKeyAttributes() instead.",
    "pendingFeatureCount": "was dropped. Use featureCount() instead.",
    "getValues": "and getDoubleValues() functions moved to QgsVectorLayerUtils.",
    "changeGeometry": "now accepts a geometry reference, not a pointer.",
    "addTopologicalPoints": "now accepts a geometry reference, not a pointer.",
    "insertSegmentVerticesForSnap": "has been removed.",
    "cache": "has been removed.",
    "hasError": "was renamed to errorCode()",
    "readXml": "does not resolve layer IDs to layers anymore. You need to call resolveReferences() afterwards.",
    "cache": "has been removed.",
    "writeAsVectorFormat": "now takes a QgsCoordinateTransform reference, not a pointer. An invalid QgsCoordinateTransform should be used instead of a null pointer if no transformation is required.",
    "setSymbologyScaleDenominator": "and symbologyScaleDenominator() were renamed to setSymbologyScale() and symbologyScale()",
    "createRenderer": "now expects a reference to QgsReadWriteContext as the second argument",
    "makeGraph": "now uses QgsFeedback for progress reporting and cancelation",
    "buildProgress": "signal was removed",
    "buildMessage": "signal was removed",
    "QgsVectorLayerDirector": "constructor now expects a reference to QgsFeatureSource as the first argument",
    "makeGraph": "now uses QgsFeedback for progress reporting and cancelation",
    "QgsZonalStatistics": "сonstructor now accepts pointer to the QgsRasterLayer instance instead of path to the raster file",
}
