#!/usr/bin/env python3
import sys
import qgis2to3.qgis2to3

from lib2to3.main import main

# sys.path.append('/usr/local/lib/python3.6/dist-packages/qgis2to3/qgis2to3/')

sys.exit(main('qgis_fixes'))
