#!/usr/bin/env python3
import sys, os
import qgis2to3.qgis2to3

from lib2to3.main import main

sys.path.append(os.path.abspath(os.path.dirname(qgis2to3.qgis2to3.__file__)))

sys.exit(main('qgis_fixes'))
